name: 'Terraform Plan & Deploy'

on:
  # Pull Requestが作成/更新されたときに「テスト（plan）」だけを走らせる
  pull_request:
    branches:
      - main
  # Pull Requestが承認（Approve）され、mainにマージされた時に「本番反映（apply）」を走らせる
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      pull-requests: write # PRにコメントを残す権限

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/663984737793/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
          service_account: 'terraform-ci-sa@gcp-lab-488301.iam.gserviceaccount.com'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      # PR作成時のみ、何が変更されるかの計画（plan）を出力する
      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan -input=false

      # mainへマージされた時のみ、実際に作成（apply）する
      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false
