name: 'Terraform Deploy'

on:
  push:
    branches:
      - main
      - master

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    # 【重要】GitHub ActionsからOIDC（キーレス認証）を行うために必要な権限
    permissions:
      contents: read
      id-token: write

    # 今回はGCPフォルダ自身がリポジトリルートになったため、terraformディレクトリへの相対パスを変更
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      # GCPのWorkload Identityへ認証
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          # 対象の受付窓口（Pool Provider）
          workload_identity_provider: 'projects/663984737793/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
          # 利用するサービスアカウント
          service_account: 'terraform-ci-sa@gcp-lab-488301.iam.gserviceaccount.com'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false

      # 自動作成まで一気に進める
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
